### ISSUE TITLE
Build Failed for multiple reason

### ISSUE THREAD

**Issue by Bento007** [HumanCellAtlas/dcp-cli#136]
https://travis-ci.org/HumanCellAtlas/dcp-cli/builds/397085403

**Comment by Bento007** [comment]
```
======================================================================
ERROR: test_python_subscriptions (test.test_dss_api.TestDssApi)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/home/travis/build/HumanCellAtlas/dcp-cli/test/test_dss_api.py", line 200, in test_python_subscriptions
    resp = client.put_subscription(es_query=query, callback_url="https://www.example.com", replica="aws")
  File "/home/travis/build/HumanCellAtlas/dcp-cli/hca/util/__init__.py", line 148, in __call__
    return self._consume_response(self._request(kwargs))
  File "/home/travis/build/HumanCellAtlas/dcp-cli/hca/util/__init__.py", line 126, in _request
    session = self.client.get_authenticated_session()
  File "/home/travis/build/HumanCellAtlas/dcp-cli/hca/util/__init__.py", line 325, in get_authenticated_session
    oauth2_client_data = self.application_secrets["installed"]
  File "/home/travis/virtualenv/python3.5.5/lib/python3.5/site-packages/tweak/__init__.py", line 166, in __getitem__
    raise KeyError(item)
KeyError: 'installed'
----------------------------------------------------------------------
```

```
======================================================================
ERROR: test_get_retry (test.test_dss_api_retry.TestDssApiRetry)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/home/travis/virtualenv/python3.4.6/lib/python3.4/site-packages/requests/adapters.py", line 445, in send
    timeout=timeout
  File "/home/travis/virtualenv/python3.4.6/lib/python3.4/site-packages/urllib3/connectionpool.py", line 731, in urlopen
    body_pos=body_pos, **response_kw)
  File "/home/travis/virtualenv/python3.4.6/lib/python3.4/site-packages/urllib3/connectionpool.py", line 731, in urlopen
    body_pos=body_pos, **response_kw)
  File "/home/travis/virtualenv/python3.4.6/lib/python3.4/site-packages/urllib3/connectionpool.py", line 731, in urlopen
    body_pos=body_pos, **response_kw)
  File "/home/travis/virtualenv/python3.4.6/lib/python3.4/site-packages/urllib3/connectionpool.py", line 731, in urlopen
    body_pos=body_pos, **response_kw)
  File "/home/travis/virtualenv/python3.4.6/lib/python3.4/site-packages/urllib3/connectionpool.py", line 731, in urlopen
    body_pos=body_pos, **response_kw)
  File "/home/travis/virtualenv/python3.4.6/lib/python3.4/site-packages/urllib3/connectionpool.py", line 731, in urlopen
    body_pos=body_pos, **response_kw)
  File "/home/travis/virtualenv/python3.4.6/lib/python3.4/site-packages/urllib3/connectionpool.py", line 731, in urlopen
    body_pos=body_pos, **response_kw)
  File "/home/travis/virtualenv/python3.4.6/lib/python3.4/site-packages/urllib3/connectionpool.py", line 731, in urlopen
    body_pos=body_pos, **response_kw)
  File "/home/travis/virtualenv/python3.4.6/lib/python3.4/site-packages/urllib3/connectionpool.py", line 731, in urlopen
    body_pos=body_pos, **response_kw)
  File "/home/travis/virtualenv/python3.4.6/lib/python3.4/site-packages/urllib3/connectionpool.py", line 731, in urlopen
    body_pos=body_pos, **response_kw)
  File "/home/travis/virtualenv/python3.4.6/lib/python3.4/site-packages/urllib3/connectionpool.py", line 711, in urlopen
    retries = retries.increment(method, url, response=response, _pool=self)
  File "/home/travis/virtualenv/python3.4.6/lib/python3.4/site-packages/urllib3/util/retry.py", line 398, in increment
    raise MaxRetryError(_pool, url, error or ResponseError(cause))
urllib3.exceptions.MaxRetryError: HTTPSConnectionPool(host='dss.dev.data.humancellatlas.org', port=443): Max retries exceeded with url: /v1/files/dd4bad35-75ec-422c-8b1b-55e2c4a3b2e4?replica=aws (Caused by ResponseError('too many 504 error responses',))
During handling of the above exception, another exception occurred:
Traceback (most recent call last):
  File "/home/travis/build/HumanCellAtlas/dcp-cli/test/test_dss_api_retry.py", line 79, in test_get_retry
    'DSS_FAKE_504_PROBABILITY': "0.5",
  File "/home/travis/build/HumanCellAtlas/dcp-cli/hca/util/__init__.py", line 134, in _request
    timeout=self.client.timeout_policy)
  File "/home/travis/virtualenv/python3.4.6/lib/python3.4/site-packages/requests/sessions.py", line 512, in request
    resp = self.send(prep, **send_kwargs)
  File "/home/travis/virtualenv/python3.4.6/lib/python3.4/site-packages/requests/sessions.py", line 622, in send
    r = adapter.send(request, **kwargs)
  File "/home/travis/virtualenv/python3.4.6/lib/python3.4/site-packages/requests/adapters.py", line 504, in send
    raise RetryError(e, request=request)
requests.exceptions.RetryError: HTTPSConnectionPool(host='dss.dev.data.humancellatlas.org', port=443): Max retries exceeded with url: /v1/files/dd4bad35-75ec-422c-8b1b-55e2c4a3b2e4?replica=aws (Caused by ResponseError('too many 504 error responses',))
----------------------------------------------------------------------
```

**Comment by Bento007** [comment]
Issue has not been see in over 19 days.
