### ISSUE TITLE
`hca dss login` broken (oauth scope change warning)

### ISSUE THREAD

**Issue by hannes-ucsc** [HumanCellAtlas/dcp-cli#138]
```
eduroam-xxx-xxx-xxx-xx:~ hannes$ virtualenv -p python3 .venvs/hca
Running virtualenv with interpreter /usr/local/bin/python3
Using base prefix '/usr/local/Cellar/python/3.6.5_1/Frameworks/Python.framework/Versions/3.6'
New python executable in /Users/hannes/.venvs/hca/bin/python3.6
Also creating executable in /Users/hannes/.venvs/hca/bin/python
Installing setuptools, pip, wheel...done.
eduroam-xxx-xxx-xxx-xx:~ hannes$ . .venvs/hca/bin/activate
(hca) eduroam-xxx-xxx-xxx-xx:~ hannes$ pip install dcp-cli
Collecting dcp-cli
  Could not find a version that satisfies the requirement dcp-cli (from versions: )
No matching distribution found for dcp-cli
(hca) eduroam-xxx-xxx-xxx-xx:~ hannes$ pip install hca
Collecting hca
  Using cached https://files.pythonhosted.org/packages/bc/44/a13f69ff3e961d9a83abe54cab505d75b9cddab0178acf303d53d6cc4484/hca-4.1.0-py2.py3-none-any.whl
Collecting six<2,>=1.10 (from hca)
  Using cached https://files.pythonhosted.org/packages/67/4b/141a581104b1f6397bfa78ac9d43d8ad29a7ca43ea90a2d863fe3056e86a/six-1.11.0-py2.py3-none-any.whl
Collecting jsonschema<3,>=2.6 (from hca)
  Using cached https://files.pythonhosted.org/packages/77/de/47e35a97b2b05c2fadbec67d44cfcdcd09b8086951b331d82de90d2912da/jsonschema-2.6.0-py2.py3-none-any.whl
Collecting dcplib<2,>=1.1.0 (from hca)
  Using cached https://files.pythonhosted.org/packages/00/c7/02861b7f52eca915a534093a94e5451b5d65828deb93ec620592184bb67f/dcplib-1.2.1-py3-none-any.whl
Collecting commonmark<1,>=0.7.4 (from hca)
  Using cached https://files.pythonhosted.org/packages/8a/5c/625ac1a93da3a672f52d947023770331b958a1100cd9889b727cde5f7ba5/CommonMark-0.7.5-py2.py3-none-any.whl
Collecting google-auth-oauthlib<2,>=0.1 (from hca)
  Using cached https://files.pythonhosted.org/packages/46/df/d1f94ee2cffe5a83721f262efe51f3b2dcdd3b616caf007b8490e824c550/google_auth_oauthlib-0.2.0-py2.py3-none-any.whl
Collecting tweak<1,>=0.6.7 (from hca)
  Using cached https://files.pythonhosted.org/packages/ed/39/65a3ee8c50896a990a29484e88520391bf72ef42d84025ff69d3f2db9583/tweak-0.6.7-py2.py3-none-any.whl
Collecting boto3<2,>=1.4 (from hca)
  Downloading https://files.pythonhosted.org/packages/d0/a6/48768566d78f51415b222f5a5a858768ebc92070f435d011121a91494e65/boto3-1.7.60-py2.py3-none-any.whl (128kB)
    100% |████████████████████████████████| 133kB 3.8MB/s
Collecting argcomplete<2,>=1.9.3 (from hca)
  Using cached https://files.pythonhosted.org/packages/31/88/ba8d8684a8a27749250c66ff7c2b408fdbc29b50da61200338ff9b2607bf/argcomplete-1.9.4-py2.py3-none-any.whl
Collecting google-auth<2,>=1.0.2 (from hca)
  Using cached https://files.pythonhosted.org/packages/53/06/6e6d5bfa4d23ee40efd772d6b681a7afecd859a9176e564b8c329382370f/google_auth-1.5.0-py2.py3-none-any.whl
Collecting jsonpointer<2,>=1.10 (from hca)
  Using cached https://files.pythonhosted.org/packages/7b/f4/90449441c1c011a733ee85739a680f2442eda2130e6a88f51804660a0289/jsonpointer-1.14-py2.py3-none-any.whl
Collecting Jinja2<3,>=2.9 (from hca)
  Using cached https://files.pythonhosted.org/packages/7f/ff/ae64bacdfc95f27a016a7bed8e8686763ba4d277a78ca76f32659220a731/Jinja2-2.10-py2.py3-none-any.whl
Collecting crcmod<2,>=1.7 (from hca)
Collecting requests<3,>=2.17 (from hca)
  Using cached https://files.pythonhosted.org/packages/65/47/7e02164a2a3db50ed6d8a6ab1d6d60b69c4c3fdf57a284257925dfc12bda/requests-2.19.1-py2.py3-none-any.whl
Collecting puremagic (from dcplib<2,>=1.1.0->hca)
  Using cached https://files.pythonhosted.org/packages/19/fe/343eabd56fd290f6a8b3e32512f8cd368f49eaf7eae57d70a987bd19ff44/puremagic-1.4-py3-none-any.whl
Collecting future (from commonmark<1,>=0.7.4->hca)
Collecting requests-oauthlib>=0.7.0 (from google-auth-oauthlib<2,>=0.1->hca)
  Using cached https://files.pythonhosted.org/packages/94/e7/c250d122992e1561690d9c0f7856dadb79d61fd4bdd0e598087dce607f6c/requests_oauthlib-1.0.0-py2.py3-none-any.whl
Collecting botocore<1.11.0,>=1.10.60 (from boto3<2,>=1.4->hca)
  Downloading https://files.pythonhosted.org/packages/75/bc/b47bc0b2262a2b808a8add6a46ea1338ad71fd4cc06f35ff6ac577b2b366/botocore-1.10.60-py2.py3-none-any.whl (4.4MB)
    100% |████████████████████████████████| 4.4MB 5.6MB/s
Collecting s3transfer<0.2.0,>=0.1.10 (from boto3<2,>=1.4->hca)
  Using cached https://files.pythonhosted.org/packages/d7/14/2a0004d487464d120c9fb85313a75cd3d71a7506955be458eebfe19a6b1d/s3transfer-0.1.13-py2.py3-none-any.whl
Collecting jmespath<1.0.0,>=0.7.1 (from boto3<2,>=1.4->hca)
  Using cached https://files.pythonhosted.org/packages/b7/31/05c8d001f7f87f0f07289a5fc0fc3832e9a57f2dbd4d3b0fee70e0d51365/jmespath-0.9.3-py2.py3-none-any.whl
Collecting pyasn1-modules>=0.2.1 (from google-auth<2,>=1.0.2->hca)
  Using cached https://files.pythonhosted.org/packages/19/02/fa63f7ba30a0d7b925ca29d034510fc1ffde53264b71b4155022ddf3ab5d/pyasn1_modules-0.2.2-py2.py3-none-any.whl
Collecting rsa>=3.1.4 (from google-auth<2,>=1.0.2->hca)
  Using cached https://files.pythonhosted.org/packages/e1/ae/baedc9cb175552e95f3395c43055a6a5e125ae4d48a1d7a924baca83e92e/rsa-3.4.2-py2.py3-none-any.whl
Collecting cachetools>=2.0.0 (from google-auth<2,>=1.0.2->hca)
  Using cached https://files.pythonhosted.org/packages/0a/58/cbee863250b31d80f47401d04f34038db6766f95dea1cc909ea099c7e571/cachetools-2.1.0-py2.py3-none-any.whl
Collecting MarkupSafe>=0.23 (from Jinja2<3,>=2.9->hca)
Collecting chardet<3.1.0,>=3.0.2 (from requests<3,>=2.17->hca)
  Using cached https://files.pythonhosted.org/packages/bc/a9/01ffebfb562e4274b6487b4bb1ddec7ca55ec7510b22e4c51f14098443b8/chardet-3.0.4-py2.py3-none-any.whl
Collecting urllib3<1.24,>=1.21.1 (from requests<3,>=2.17->hca)
  Using cached https://files.pythonhosted.org/packages/bd/c9/6fdd990019071a4a32a5e7cb78a1d92c53851ef4f56f62a3486e6a7d8ffb/urllib3-1.23-py2.py3-none-any.whl
Collecting certifi>=2017.4.17 (from requests<3,>=2.17->hca)
  Using cached https://files.pythonhosted.org/packages/7c/e6/92ad559b7192d846975fc916b65f667c7b8c3a32bea7372340bfe9a15fa5/certifi-2018.4.16-py2.py3-none-any.whl
Collecting idna<2.8,>=2.5 (from requests<3,>=2.17->hca)
  Using cached https://files.pythonhosted.org/packages/4b/2a/0276479a4b3caeb8a8c1af2f8e4355746a97fab05a372e4a2c6a6b876165/idna-2.7-py2.py3-none-any.whl
Collecting argparse (from puremagic->dcplib<2,>=1.1.0->hca)
  Using cached https://files.pythonhosted.org/packages/f2/94/3af39d34be01a24a6e65433d19e107099374224905f1e0cc6bbe1fd22a2f/argparse-1.4.0-py2.py3-none-any.whl
Collecting oauthlib>=0.6.2 (from requests-oauthlib>=0.7.0->google-auth-oauthlib<2,>=0.1->hca)
  Using cached https://files.pythonhosted.org/packages/e6/d1/ddd9cfea3e736399b97ded5c2dd62d1322adef4a72d816f1ed1049d6a179/oauthlib-2.1.0-py2.py3-none-any.whl
Collecting docutils>=0.10 (from botocore<1.11.0,>=1.10.60->boto3<2,>=1.4->hca)
  Using cached https://files.pythonhosted.org/packages/36/fa/08e9e6e0e3cbd1d362c3bbee8d01d0aedb2155c4ac112b19ef3cae8eed8d/docutils-0.14-py3-none-any.whl
Collecting python-dateutil<3.0.0,>=2.1; python_version >= "2.7" (from botocore<1.11.0,>=1.10.60->boto3<2,>=1.4->hca)
  Using cached https://files.pythonhosted.org/packages/cf/f5/af2b09c957ace60dcfac112b669c45c8c97e32f94aa8b56da4c6d1682825/python_dateutil-2.7.3-py2.py3-none-any.whl
Collecting pyasn1<0.5.0,>=0.4.1 (from pyasn1-modules>=0.2.1->google-auth<2,>=1.0.2->hca)
  Using cached https://files.pythonhosted.org/packages/a0/70/2c27740f08e477499ce19eefe05dbcae6f19fdc49e9e82ce4768be0643b9/pyasn1-0.4.3-py2.py3-none-any.whl
Installing collected packages: six, jsonschema, crcmod, docutils, python-dateutil, jmespath, botocore, s3transfer, boto3, argparse, puremagic, dcplib, future, commonmark, chardet, urllib3, certifi, idna, requests, oauthlib, requests-oauthlib, pyasn1, pyasn1-modules, rsa, cachetools, google-auth, google-auth-oauthlib, tweak, argcomplete, jsonpointer, MarkupSafe, Jinja2, hca
Successfully installed Jinja2-2.10 MarkupSafe-1.0 argcomplete-1.9.4 argparse-1.4.0 boto3-1.7.60 botocore-1.10.60 cachetools-2.1.0 certifi-2018.4.16 chardet-3.0.4 commonmark-0.7.5 crcmod-1.7 dcplib-1.2.1 docutils-0.14 future-0.16.0 google-auth-1.5.0 google-auth-oauthlib-0.2.0 hca-4.1.0 idna-2.7 jmespath-0.9.3 jsonpointer-1.14 jsonschema-2.6.0 oauthlib-2.1.0 puremagic-1.4 pyasn1-0.4.3 pyasn1-modules-0.2.2 python-dateutil-2.7.3 requests-2.19.1 requests-oauthlib-1.0.0 rsa-3.4.2 s3transfer-0.1.13 six-1.11.0 tweak-0.6.7 urllib3-1.23
(hca) eduroam-xxx-xxx-xxx-xx:~ hannes$ rm -rf ~/.config/hca/
aHR0cHM6Ly9kc3MuZGF0YS5odW1hbmNlbGxhdGxhcy5vcmcvdjEvc3dhZ2dlci5qc29u.json  config.json
(hca) eduroam-xxx-xxx-xxx-xx:~ hannes$ rm -rf ~/.config/hca
(hca) eduroam-xxx-xxx-xxx-xx:~ hannes$ hca dss login
Please visit this URL to authorize this application: https://accounts.google.com/o/oauth2/auth?response_type=code&client_id=803155065464-8hgbqc16nve9hm78lqrvfbcpv5oh275q.apps.googleusercontent.com&redirect_uri=http%3A%2F%2Flocalhost%3A8080%2F&scope=https%3A%2F%2Fwww.googleapis.com%2Fauth%2Fuserinfo.email&state=ZoQIs3O8WlO5bRzwO49ZmrVexXufd6&access_type=offline
Traceback (most recent call last):
  File "/Users/hannes/.venvs/hca/bin/hca", line 13, in <module>
    cli.main()
  File "/Users/hannes/.venvs/hca/lib/python3.6/site-packages/hca/cli.py", line 73, in main
    result = parsed_args.entry_point(parsed_args)
  File "/Users/hannes/.venvs/hca/lib/python3.6/site-packages/hca/util/__init__.py", line 432, in arg_forwarder
    return command(**command_args)
  File "/Users/hannes/.venvs/hca/lib/python3.6/site-packages/hca/util/__init__.py", line 292, in login
    credentials = flow.run_local_server()
  File "/Users/hannes/.venvs/hca/lib/python3.6/site-packages/google_auth_oauthlib/flow.py", line 420, in run_local_server
    self.fetch_token(authorization_response=authorization_response)
  File "/Users/hannes/.venvs/hca/lib/python3.6/site-packages/google_auth_oauthlib/flow.py", line 241, in fetch_token
    self.client_config['token_uri'], **kwargs)
  File "/Users/hannes/.venvs/hca/lib/python3.6/site-packages/requests_oauthlib/oauth2_session.py", line 244, in fetch_token
    self._client.parse_request_body_response(r.text, scope=self.scope)
  File "/Users/hannes/.venvs/hca/lib/python3.6/site-packages/oauthlib/oauth2/rfc6749/clients/base.py", line 411, in parse_request_body_response
    self.token = parse_token_response(body, scope=scope)
  File "/Users/hannes/.venvs/hca/lib/python3.6/site-packages/oauthlib/oauth2/rfc6749/parameters.py", line 379, in parse_token_response
    validate_token_parameters(params)
  File "/Users/hannes/.venvs/hca/lib/python3.6/site-packages/oauthlib/oauth2/rfc6749/parameters.py", line 409, in validate_token_parameters
    raise w
Warning: Scope has changed from "https://www.googleapis.com/auth/userinfo.email" to "https://www.googleapis.com/auth/plus.me https://www.googleapis.com/auth/userinfo.email".
```

**Comment by Bento007** [comment]
I'll try to reproduce

**Comment by Bento007** [comment]
I was successfully able to reproduce the error.
