### ISSUE TITLE
CLI doesn't log actual response body for 500 responses

### ISSUE THREAD

**Issue by hannes-ucsc** [HumanCellAtlas/dcp-cli#172]
```
$ hca dss get-bundle --uuid 1e276fdd-d885-4a18-b5b8-df33f1347c1a --replica gcp
Traceback (most recent call last):
  File "/Users/hannes/workspace/hca/metadata-api/.venv/lib/python3.6/site-packages/requests/adapters.py", line 445, in send
    timeout=timeout
  File "/Users/hannes/workspace/hca/metadata-api/.venv/lib/python3.6/site-packages/urllib3/connectionpool.py", line 731, in urlopen
    body_pos=body_pos, **response_kw)
  File "/Users/hannes/workspace/hca/metadata-api/.venv/lib/python3.6/site-packages/urllib3/connectionpool.py", line 731, in urlopen
    body_pos=body_pos, **response_kw)
  File "/Users/hannes/workspace/hca/metadata-api/.venv/lib/python3.6/site-packages/urllib3/connectionpool.py", line 731, in urlopen
    body_pos=body_pos, **response_kw)
  [Previous line repeated 6 more times]
  File "/Users/hannes/workspace/hca/metadata-api/.venv/lib/python3.6/site-packages/urllib3/connectionpool.py", line 711, in urlopen
    retries = retries.increment(method, url, response=response, _pool=self)
  File "/Users/hannes/workspace/hca/metadata-api/.venv/lib/python3.6/site-packages/urllib3/util/retry.py", line 398, in increment
    raise MaxRetryError(_pool, url, error or ResponseError(cause))
urllib3.exceptions.MaxRetryError: HTTPSConnectionPool(host='dss.integration.data.humancellatlas.org', port=443): Max retries exceeded with url: /v1/bundles/1e276fdd-d885-4a18-b5b8-df33f1347c1a?replica=gcp (Caused by ResponseError('too many 500 error responses',))

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/Users/hannes/workspace/hca/metadata-api/.venv/bin/hca", line 11, in <module>
    sys.exit(main())
  File "/Users/hannes/workspace/hca/metadata-api/.venv/lib/python3.6/site-packages/hca/cli.py", line 73, in main
    result = parsed_args.entry_point(parsed_args)
  File "/Users/hannes/workspace/hca/metadata-api/.venv/lib/python3.6/site-packages/hca/util/__init__.py", line 153, in _cli_call
    return self._consume_response(self._request(vars(cli_args)))
  File "/Users/hannes/workspace/hca/metadata-api/.venv/lib/python3.6/site-packages/hca/util/__init__.py", line 136, in _request
    timeout=self.client.timeout_policy)
  File "/Users/hannes/workspace/hca/metadata-api/.venv/lib/python3.6/site-packages/requests/sessions.py", line 512, in request
    resp = self.send(prep, **send_kwargs)
  File "/Users/hannes/workspace/hca/metadata-api/.venv/lib/python3.6/site-packages/requests/sessions.py", line 622, in send
    r = adapter.send(request, **kwargs)
  File "/Users/hannes/workspace/hca/metadata-api/.venv/lib/python3.6/site-packages/requests/adapters.py", line 504, in send
    raise RetryError(e, request=request)
requests.exceptions.RetryError: HTTPSConnectionPool(host='dss.integration.data.humancellatlas.org', port=443): Max retries exceeded with url: /v1/bundles/1e276fdd-d885-4a18-b5b8-df33f1347c1a?replica=gcp (Caused by ResponseError('too many 500 error responses',))
```

I would expect that when the retries are exhausted, that the user should see the original response which should look like this:

```
$ http 'https://dss.integration.data.humancellatlas.org/v1/bundles/1e276fdd-d885-4a18-b5b8-df33f1347c1a?replica=gcp'
HTTP/1.1 500 Internal Server Error
Access-Control-Allow-Headers: Authorization,Content-Type,X-Amz-Date,X-Amz-Security-Token,X-Api-Key
Access-Control-Allow-Origin: *
Connection: keep-alive
Content-Length: 2757
Content-Type: application/problem+json
Date: Tue, 14 Aug 2018 19:55:40 GMT
Strict-Transport-Security: max-age=31536000; includeSubDomains; preload
X-Amzn-Trace-Id: Root=1-5b7333bc-4861bd953dbf6f46564456ab;Sampled=0
x-amz-apigw-id: LoUFZEdNoAMFR2Q=
x-amzn-RequestId: 05205532-9ffc-11e8-bb2a-2be1ea8085f3

{
    "code": "unhandled_exception",
    "stacktrace": "Traceback (most recent call last):\n  File \"/var/task/chalicelib/dss/error.py\", line 26, in wrapper\n    return func(*args, **kwargs)\n  File \"/var/task/chalicelib/dss/api/bundles/__init__.py\", line 49, in get\n    bundle_metadata = get_bundle_manifest(uuid, _replica, version)\n  File \"/var/task/chalicelib/dss/storage/bundles.py\", line 37, in get_bundle_manifest\n    if tombstone_exists(uuid, None) or (version and tombstone_exists(uuid, version)):\n  File \"/var/task/chalicelib/dss/storage/bundles.py\", line 32, in tombstone_exists\n    return test_object_exists(handle, bucket, TombstoneID(uuid=uuid, version=version).to_key())\n  File \"/var/task/chalicelib/dss/storage/blobstore.py\", line 30, in test_object_exists\n    blobstore.get_user_metadata(bucket, match)\n  File \"/var/task/cloud_blobstore/gs.py\", line 17, in wrapped\n    return meth(*args, **kwargs)\n  File \"/var/task/cloud_blobstore/gs.py\", line 255, in get_user_metadata\n    response = bucket_obj.get_blob(key)\n  File \"/var/task/google/cloud/storage/bucket.py\", line 396, in get_blob\n    _target_object=blob,\n  File \"/var/task/google/cloud/_http.py\", line 290, in api_request\n    headers=headers, target_object=_target_object)\n  File \"/var/task/google/cloud/_http.py\", line 183, in _make_request\n    return self._do_request(method, url, headers, data, target_object)\n  File \"/var/task/google/cloud/_http.py\", line 212, in _do_request\n    url=url, method=method, headers=headers, data=data)\n  File \"/var/task/chalicelib/dss/config.py\", line 148, in request\n    return super().request(*args, **kwargs)\n  File \"/var/task/google/auth/transport/requests.py\", line 183, in request\n    self._auth_request, method, url, request_headers)\n  File \"/var/task/google/auth/credentials.py\", line 121, in before_request\n    self.refresh(request)\n  File \"/var/task/google/oauth2/service_account.py\", line 322, in refresh\n    request, self._token_uri, assertion)\n  File \"/var/task/google/oauth2/_client.py\", line 144, in jwt_grant\n    response_data = _token_endpoint_request(request, token_uri, body)\n  File \"/var/task/google/oauth2/_client.py\", line 110, in _token_endpoint_request\n    _handle_error_response(response_body)\n  File \"/var/task/google/oauth2/_client.py\", line 60, in _handle_error_response\n    error_details, response_body)\ngoogle.auth.exceptions.RefreshError: ('invalid_grant: Invalid JWT Signature.', '{\\n  \"error\" : \"invalid_grant\",\\n  \"error_description\" : \"Invalid JWT Signature.\"\\n}')\n",
    "status": 500,
    "title": "('invalid_grant: Invalid JWT Signature.', '{\\n  \"error\" : \"invalid_grant\",\\n  \"error_description\" : \"Invalid JWT Signature.\"\\n}')"
}
```

The original stack is really important when we try to diagnose these 500 errors since the DSS-internal logs don't contain them (that may be another bug) and the user's console log is the only place to see the DSS exception. 

Indepentently, I'm also a bit sceptical thatretrying on 500 errors is the right thing to do.

**Comment by kozbo** [comment]
We should log retries at DEBUG level until the actual error happens on the lsat retry.

**Comment by Bento007** [comment]
This should be fixed.
