### ISSUE TITLE
Don't retry if endpoint hostname does not resolve

### ISSUE THREAD

**Issue by hannes-ucsc** [HumanCellAtlas/dcp-cli#191]
The current retry logic is too persistent. Initializing a DSSClient instance with an non-existant host name:

```
client = DSSClient(swagger_url='https://dss.fatfinger.data.humancellatlas.org/v1/swagger.json')
client.timeout_policy = Timeout(connect=10, read=40)
```

seems to enter a retry loop:

```
Testing started at 5:05 PM ...
/Users/hannes/workspace/hca/metadata-api/.venv/bin/python /Applications/PyCharm.app/Contents/helpers/pycharm/_jb_unittest_runner.py --target test.TestAccessorApi.test_one_bundle
Launching unittests with arguments python -m unittest test.TestAccessorApi.test_one_bundle in /Users/hannes/workspace/hca/metadata-api/test
2018-09-24 17:05:20,319 INFO tweak MainThread: Loaded configuration from /Users/hannes/workspace/hca/metadata-api/.venv/lib/python3.6/site-packages/hca/default_config.json
2018-09-24 17:05:20,319 INFO tweak MainThread: Loaded configuration from /Users/hannes/.config/hca/config.json
2018-09-24 17:05:20,995 WARNING urllib3.connectionpool MainThread: Retrying (RetryPolicy(total=9, connect=None, read=10, redirect=3, status=10)) after connection broken by 'NewConnectionError('<urllib3.connection.VerifiedHTTPSConnection object at 0x103461400>: Failed to establish a new connection: [Errno 8] nodename nor servname provided, or not known',)': /v1/swagger.json
2018-09-24 17:05:21,200 WARNING urllib3.connectionpool MainThread: Retrying (RetryPolicy(total=8, connect=None, read=10, redirect=3, status=10)) after connection broken by 'NewConnectionError('<urllib3.connection.VerifiedHTTPSConnection object at 0x103461518>: Failed to establish a new connection: [Errno 8] nodename nor servname provided, or not known',)': /v1/swagger.json
2018-09-24 17:05:21,609 WARNING urllib3.connectionpool MainThread: Retrying (RetryPolicy(total=7, connect=None, read=10, redirect=3, status=10)) after connection broken by 'NewConnectionError('<urllib3.connection.VerifiedHTTPSConnection object at 0x103461588>: Failed to establish a new connection: [Errno 8] nodename nor servname provided, or not known',)': /v1/swagger.json
2018-09-24 17:05:22,419 WARNING urllib3.connectionpool MainThread: Retrying (RetryPolicy(total=6, connect=None, read=10, redirect=3, status=10)) after connection broken by 'NewConnectionError('<urllib3.connection.VerifiedHTTPSConnection object at 0x103461630>: Failed to establish a new connection: [Errno 8] nodename nor servname provided, or not known',)': /v1/swagger.json
2018-09-24 17:05:24,027 WARNING urllib3.connectionpool MainThread: Retrying (RetryPolicy(total=5, connect=None, read=10, redirect=3, status=10)) after connection broken by 'NewConnectionError('<urllib3.connection.VerifiedHTTPSConnection object at 0x1034616a0>: Failed to establish a new connection: [Errno 8] nodename nor servname provided, or not known',)': /v1/swagger.json
2018-09-24 17:05:27,237 WARNING urllib3.connectionpool MainThread: Retrying (RetryPolicy(total=4, connect=None, read=10, redirect=3, status=10)) after connection broken by 'NewConnectionError('<urllib3.connection.VerifiedHTTPSConnection object at 0x103461860>: Failed to establish a new connection: [Errno 8] nodename nor servname provided, or not known',)': /v1/swagger.json
2018-09-24 17:05:33,643 WARNING urllib3.connectionpool MainThread: Retrying (RetryPolicy(total=3, connect=None, read=10, redirect=3, status=10)) after connection broken by 'NewConnectionError('<urllib3.connection.VerifiedHTTPSConnection object at 0x103461978>: Failed to establish a new connection: [Errno 8] nodename nor servname provided, or not known',)': /v1/swagger.json
2018-09-24 17:05:46,449 WARNING urllib3.connectionpool MainThread: Retrying (RetryPolicy(total=2, connect=None, read=10, redirect=3, status=10)) after connection broken by 'NewConnectionError('<urllib3.connection.VerifiedHTTPSConnection object at 0x103461a90>: Failed to establish a new connection: [Errno 8] nodename nor servname provided, or not known',)': /v1/swagger.json
2018-09-24 17:06:12,056 WARNING urllib3.connectionpool MainThread: Retrying (RetryPolicy(total=1, connect=None, read=10, redirect=3, status=10)) after connection broken by 'NewConnectionError('<urllib3.connection.VerifiedHTTPSConnection object at 0x103461ba8>: Failed to establish a new connection: [Errno 8] nodename nor servname provided, or not known',)': /v1/swagger.json
```
and when you Ctrl-C prints the following:

```
Traceback (most recent call last):
  File "/Users/hannes/workspace/hca/metadata-api/.venv/lib/python3.6/site-packages/urllib3/connection.py", line 171, in _new_conn
    (self._dns_host, self.port), self.timeout, **extra_kw)
  File "/Users/hannes/workspace/hca/metadata-api/.venv/lib/python3.6/site-packages/urllib3/util/connection.py", line 56, in create_connection
    for res in socket.getaddrinfo(host, port, family, socket.SOCK_STREAM):
  File "/usr/local/Cellar/python/3.6.5_1/Frameworks/Python.framework/Versions/3.6/lib/python3.6/socket.py", line 745, in getaddrinfo
    for res in _socket.getaddrinfo(host, port, family, type, proto, flags):
socket.gaierror: [Errno 8] nodename nor servname provided, or not known

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/Users/hannes/workspace/hca/metadata-api/.venv/lib/python3.6/site-packages/urllib3/connectionpool.py", line 600, in urlopen
    chunked=chunked)
  File "/Users/hannes/workspace/hca/metadata-api/.venv/lib/python3.6/site-packages/urllib3/connectionpool.py", line 343, in _make_request
    self._validate_conn(conn)
  File "/Users/hannes/workspace/hca/metadata-api/.venv/lib/python3.6/site-packages/urllib3/connectionpool.py", line 849, in _validate_conn
    conn.connect()
  File "/Users/hannes/workspace/hca/metadata-api/.venv/lib/python3.6/site-packages/urllib3/connection.py", line 314, in connect
    conn = self._new_conn()
  File "/Users/hannes/workspace/hca/metadata-api/.venv/lib/python3.6/site-packages/urllib3/connection.py", line 180, in _new_conn
    self, "Failed to establish a new connection: %s" % e)
urllib3.exceptions.NewConnectionError: <urllib3.connection.VerifiedHTTPSConnection object at 0x103461cc0>: Failed to establish a new connection: [Errno 8] nodename nor servname provided, or not known

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/Applications/PyCharm.app/Contents/helpers/pycharm/_jb_unittest_runner.py", line 35, in <module>
    main(argv=args, module=None, testRunner=unittestpy.TeamcityTestRunner, buffer=not JB_DISABLE_BUFFERING)
  File "/usr/local/Cellar/python/3.6.5_1/Frameworks/Python.framework/Versions/3.6/lib/python3.6/unittest/main.py", line 95, in __init__
    self.runTests()
  File "/usr/local/Cellar/python/3.6.5_1/Frameworks/Python.framework/Versions/3.6/lib/python3.6/unittest/main.py", line 256, in runTests
    self.result = testRunner.run(self.test)
  File "/Applications/PyCharm.app/Contents/helpers/pycharm/teamcity/unittestpy.py", line 304, in run
    return super(TeamcityTestRunner, self).run(test)
  File "/usr/local/Cellar/python/3.6.5_1/Frameworks/Python.framework/Versions/3.6/lib/python3.6/unittest/runner.py", line 176, in run
    test(result)
  File "/usr/local/Cellar/python/3.6.5_1/Frameworks/Python.framework/Versions/3.6/lib/python3.6/unittest/suite.py", line 84, in __call__
    return self.run(*args, **kwds)
  File "/usr/local/Cellar/python/3.6.5_1/Frameworks/Python.framework/Versions/3.6/lib/python3.6/unittest/suite.py", line 122, in run
    test(result)
  File "/usr/local/Cellar/python/3.6.5_1/Frameworks/Python.framework/Versions/3.6/lib/python3.6/unittest/suite.py", line 84, in __call__
    return self.run(*args, **kwds)
  File "/usr/local/Cellar/python/3.6.5_1/Frameworks/Python.framework/Versions/3.6/lib/python3.6/unittest/suite.py", line 122, in run
    test(result)
  File "/usr/local/Cellar/python/3.6.5_1/Frameworks/Python.framework/Versions/3.6/lib/python3.6/unittest/case.py", line 653, in __call__
    return self.run(*args, **kwds)
  File "/usr/local/Cellar/python/3.6.5_1/Frameworks/Python.framework/Versions/3.6/lib/python3.6/unittest/case.py", line 605, in run
    testMethod()
  File "/Users/hannes/workspace/hca/metadata-api/test/test.py", line 46, in test_one_bundle
    client = dss_client(deployment)
  File "/Users/hannes/workspace/hca/metadata-api/src/humancellatlas/data/metadata/helpers/dss.py", line 93, in dss_client
    client = DSSClient(swagger_url='https://dss.fatfinger.data.humancellatlas.org/v1/swagger.json')
  File "/Users/hannes/workspace/hca/metadata-api/.venv/lib/python3.6/site-packages/hca/dss/__init__.py", line 37, in __init__
    super(DSSClient, self).__init__(*args, **kwargs)
  File "/Users/hannes/workspace/hca/metadata-api/.venv/lib/python3.6/site-packages/hca/util/__init__.py", line 217, in __init__
    self.__class__.__doc__ = _md2rst(self.swagger_spec["info"]["description"])
  File "/Users/hannes/workspace/hca/metadata-api/.venv/lib/python3.6/site-packages/hca/util/__init__.py", line 266, in swagger_spec
    res = self.get_session().get(self.swagger_url)
  File "/Users/hannes/workspace/hca/metadata-api/.venv/lib/python3.6/site-packages/requests/sessions.py", line 525, in get
    return self.request('GET', url, **kwargs)
  File "/Users/hannes/workspace/hca/metadata-api/.venv/lib/python3.6/site-packages/requests/sessions.py", line 512, in request
    resp = self.send(prep, **send_kwargs)
  File "/Users/hannes/workspace/hca/metadata-api/.venv/lib/python3.6/site-packages/requests/sessions.py", line 622, in send
    r = adapter.send(request, **kwargs)
  File "/Users/hannes/workspace/hca/metadata-api/.venv/lib/python3.6/site-packages/requests/adapters.py", line 445, in send
    timeout=timeout
  File "/Users/hannes/workspace/hca/metadata-api/.venv/lib/python3.6/site-packages/urllib3/connectionpool.py", line 667, in urlopen
    **response_kw)
  File "/Users/hannes/workspace/hca/metadata-api/.venv/lib/python3.6/site-packages/urllib3/connectionpool.py", line 667, in urlopen
    **response_kw)
  File "/Users/hannes/workspace/hca/metadata-api/.venv/lib/python3.6/site-packages/urllib3/connectionpool.py", line 667, in urlopen
    **response_kw)
  [Previous line repeated 5 more times]
  File "/Users/hannes/workspace/hca/metadata-api/.venv/lib/python3.6/site-packages/urllib3/connectionpool.py", line 639, in urlopen
    retries.sleep()
  File "/Users/hannes/workspace/hca/metadata-api/.venv/lib/python3.6/site-packages/urllib3/util/retry.py", line 281, in sleep
    self._sleep_backoff()
  File "/Users/hannes/workspace/hca/metadata-api/.venv/lib/python3.6/site-packages/urllib3/util/retry.py", line 265, in _sleep_backoff
    time.sleep(backoff)
KeyboardInterrupt

Process finished with exit code 1
```

There should be no retries if the host name of the endpoint can't be resolved.

**Comment by hannes-ucsc** [comment]
I also believe that retrying so persistently on every 500 is not a good idea: https://github.com/HumanCellAtlas/data-store/issues/1597. It means that essentially every bug in DSS manifests itself in a hung client. Some 500 errors can be resolved by retrying, others can't. There is no way of knowing which ones do so it's probably better to never retry on a 500.

**Comment by kislyuk** [comment]
Retrying on 500 series codes with truncated exponential backoff is a best practice.

**Comment by hannes-ucsc** [comment]
You got a point. Should we log 500 and connection errors with high severity (like WARNING) before retrying? This is in contrast to 301/302 retries which don't need to be logged with WARNING, but maybe with INFO or DEBUG.

**Comment by kislyuk** [comment]
Yep, we definitely should. That's a good point.
