### ISSUE TITLE
Errors with `pip install hca`

### ISSUE THREAD

**Issue by dirtygardner** [HumanCellAtlas/dcp-cli#210]
`uname -a` : Linux debian 4.9.0-8-amd64 #1 SMP Debian 4.9.130-2 (2018-10-27) x86_64 GNU/Linux
`lsb_release -a` : Debian GNU/Linux 9.6 (stretch)
`python --version` : Python 2.7.13

`pip install hca`
Collecting botocore<1.11.0,>=1.10.84 (from boto3<1.8,>=1.7->hca)
  Downloading https://files.pythonhosted.org/packages/01/b7/cb08cd1af2bb0d0dfb393101a93b6ab6fb80f109ab7b37f2f34386c11351/botocore-1.10.84-py2.py3-none-any.whl (4.5MB)
Exception:
Traceback (most recent call last):
  File "/usr/lib/python2.7/dist-packages/pip/basecommand.py", line 215, in main
    status = self.run(options, args)
  File "/usr/lib/python2.7/dist-packages/pip/commands/install.py", line 353, in run
    wb.build(autobuilding=True)
  File "/usr/lib/python2.7/dist-packages/pip/wheel.py", line 749, in build
    self.requirement_set.prepare_files(self.finder)
  File "/usr/lib/python2.7/dist-packages/pip/req/req_set.py", line 380, in prepare_files
    ignore_dependencies=self.ignore_dependencies))
  File "/usr/lib/python2.7/dist-packages/pip/req/req_set.py", line 620, in _prepare_file
    session=self.session, hashes=hashes)
  File "/usr/lib/python2.7/dist-packages/pip/download.py", line 821, in unpack_url
    hashes=hashes
  File "/usr/lib/python2.7/dist-packages/pip/download.py", line 659, in unpack_http_url
    hashes)
  File "/usr/lib/python2.7/dist-packages/pip/download.py", line 882, in _download_http_url
    _download_url(resp, link, content_file, hashes)
  File "/usr/lib/python2.7/dist-packages/pip/download.py", line 603, in _download_url
    hashes.check_against_chunks(downloaded_chunks)
  File "/usr/lib/python2.7/dist-packages/pip/utils/hashes.py", line 46, in check_against_chunks
    for chunk in chunks:
  File "/usr/lib/python2.7/dist-packages/pip/download.py", line 571, in written_chunks
    for chunk in chunks:
  File "/usr/lib/python2.7/dist-packages/pip/utils/ui.py", line 139, in iter
    for x in it:
  File "/usr/lib/python2.7/dist-packages/pip/download.py", line 560, in resp_read
    decode_content=False):
  File "/usr/share/python-wheels/urllib3-1.19.1-py2.py3-none-any.whl/urllib3/response.py", line 432, in stream
    data = self.read(amt=amt, decode_content=decode_content)
  File "/usr/share/python-wheels/urllib3-1.19.1-py2.py3-none-any.whl/urllib3/response.py", line 397, in read
    raise IncompleteRead(self._fp_bytes_read, self.length_remaining)
  File "/usr/lib/python2.7/contextlib.py", line 35, in __exit__
    self.gen.throw(type, value, traceback)
  File "/usr/share/python-wheels/urllib3-1.19.1-py2.py3-none-any.whl/urllib3/response.py", line 312, in _error_catcher
    raise ReadTimeoutError(self._pool, None, 'Read timed out.')
ReadTimeoutError: HTTPSConnectionPool(host='files.pythonhosted.org', port=443): Read timed out.

**Comment by sampierson** [comment]
@dirtygardner how many times did you try?  Reading the error, it looks like there may have been a network problem between you computer and `files.pythonhosted.org`.  That site is not a part of the HCA, and I'm guessing is part of the infrastructure that lives behind pypi.org.   Network issues being transient, perhaps it has gone.  Please try your installation again.

**Comment by dirtygardner** [comment]
Attempted more than once and don't recall how many times. Good point about keeping track.
2018-11-27-02.30.00-UTC install failed with same error as in [original post](https://github.com/HumanCellAtlas/dcp-cli/issues/210#issue-384349042)
2018-11-27-02.35.00-UTC install failed with same error as in [original post](https://github.com/HumanCellAtlas/dcp-cli/issues/210#issue-384349042)
2018-11-27-02.50.33-UTC install failed with same error as in [original post](https://github.com/HumanCellAtlas/dcp-cli/issues/210#issue-384349042)
Will attempt again with more stable connection.

**Comment by dirtygardner** [comment]
2018-11-28-03.31.41-UTC `pip install hca` successful
