### ISSUE TITLE
download-manifest command returns 404

### ISSUE THREAD

**Issue by kozbo** [HumanCellAtlas/dcp-cli#327]
End user reports that he gets a 404 when trying to do a download-manifest from a manifest file created from the UI for the Immune Cell Atlas data set. 

**Reproducible** for me on hca 5.2.0, Python 3.6.4    

Zenhub [ticket #125](https://humancellatlas.zendesk.com/agent/tickets/125)  -- this from the end user

I followed your link, and I was able to download the manifest file. And then, I just tried to download the entire project (BM1 to BM8) using CLI, but got a bunch of errors:

```
$ hca dss download-manifest --manifest hca-manifest-357ed11f-6006-46c2-b8d8-7760acba3dc5.tsv --replica aws

Traceback (most recent call last):
  File "/var/task/chalicelib/dss/error.py", line 59, in wrapper
    return func(*args, **kwargs)
  File "/var/task/chalicelib/dss/api/bundles/__init__.py", line 49, in get
    raise DSSException(404, "not_found", "Cannot find bundle!")
dss.error.DSSException
```

I looked at the manifest file, especially the first and second c[https://app.zenhub.com/files/93565055/139c0c1d-13e5-421b-8107-6a9e62bbd3c8/download](https://app.zenhub.com/files/93565055/139c0c1d-13e5-421b-8107-6a9e62bbd3c8/download)olumn, and I'm not sure what I'm seeing is actually right. As shown below, two UUIDs are concatenated with double vertical bars (looks like "or" operator to me, but anyway). Same for the `bundle_version` column:

bundle_uuid
0bbb26b9-8c8f-444a-989e-1981d8e1fd09 || 4dbed2a8-3755-47ff-9808-d602ae4985f9

bundle_version
2018-11-29T153103.948395Z || 2018-12-13T000432.880404Z

-------------
I verified that the manifest file in the current deployment of prod created a piped entry as above for each fastq file, and that a truncated manifest file failed immediately on download. (attached)

```
INFO:hca:Downloading bundle 72a60bff-a727-4c86-b6f0-938d02701f2e || cc5cb847-caf5-4135-a274-d203032877de version 2018-11-29T153131.476016Z || 2018-12-13T000102.935762Z ...
WARNING:hca:Bundle 72a60bff-a727-4c86-b6f0-938d02701f2e || cc5cb847-caf5-4135-a274-d203032877de failed to download
Traceback (most recent call last):
  File "/Users/kosborn/Documents/dev/hca/py364/lib/python3.6/site-packages/hca/dss/__init__.py", line 479, in _download_manifest_tasks
    min_delay_seconds=min_delay_seconds):
  File "/Users/kosborn/Documents/dev/hca/py364/lib/python3.6/site-packages/hca/dss/__init__.py", line 151, in _download_tasks
    bundle = self.get_bundle(uuid=bundle_uuid, replica=replica, version=version if version else None)["bundle"]
  File "/Users/kosborn/Documents/dev/hca/py364/lib/python3.6/site-packages/hca/util/__init__.py", line 207, in __call__
    return self._consume_response(self._request(kwargs))
  File "/Users/kosborn/Documents/dev/hca/py364/lib/python3.6/site-packages/hca/util/__init__.py", line 195, in _request
    raise SwaggerAPIException(response=res)
hca.util.exceptions.SwaggerAPIException: not_found: Cannot find bundle! (HTTP 404). Details:
Traceback (most recent call last):
  File "/var/task/chalicelib/dss/error.py", line 59, in wrapper
    return func(*args, **kwargs)
  File "/var/task/chalicelib/dss/api/bundles/__init__.py", line 54, in get
    raise DSSException(404, "not_found", "Cannot find bundle!")
dss.error.DSSException

Traceback (most recent call last):
  File "/Users/kosborn/Documents/dev/hca/py364/bin/hca", line 11, in <module>
    sys.exit(main())
  File "/Users/kosborn/Documents/dev/hca/py364/lib/python3.6/site-packages/hca/cli.py", line 136, in main
    result = parsed_args.entry_point(parsed_args)
  File "/Users/kosborn/Documents/dev/hca/py364/lib/python3.6/site-packages/hca/util/__init__.py", line 551, in arg_forwarder
    return command(**command_args)
  File "/Users/kosborn/Documents/dev/hca/py364/lib/python3.6/site-packages/hca/dss/__init__.py", line 453, in download_manifest
    raise RuntimeError(bundle_error_str + (' and ' if bundle_errors and file_errors else '') + file_error_str)
RuntimeError: 1 bundle(s) failed to download
```

**Comment by jessebrennan** [comment]
Thanks for finding this. The easiest workarount for now is just to use the `_v2` download (soon to become configurable via a `--layout` option in #317

**Comment by theathorn** [comment]
Is this related to databiosphere/azul#955?

**Comment by jessebrennan** [comment]
@theathorn yes, from my understanding  DataBiosphere/azul#955 will fix this.

**Comment by hannes-ucsc** [comment]
As @jessebrennan points out, #955 will ultimately fix this. However I think the CLI—or even better the DSS—should validate the syntax of the bundle reference (UUID and version). The status code returned by the DSS should not be 404 but rather 400 due to invalid syntax of bundle UUID and version. I'd prefer the DSS to do that, rather than baking in an assumption of what constitutes a valid version into the CLI.

Assigning to @kozbo for triage.

**Comment by kozbo** [comment]
Closing this issue, and opening one for the 404 return.

**Comment by hannes-ucsc** [comment]
The fix will appear in production this week (hopefully, Wed). Updating the CLI is not necessary to get the fix.
