### ISSUE TITLE
`get-collections` fails with `not a valid key=value pair...`

### ISSUE THREAD

**Issue by natanlao** [HumanCellAtlas/dcp-cli#349]
Doing `hca dss get-collections` fails with the following traceback:

```
Traceback (most recent call last):
  File "/home/natan/hca/dcp-cli/venv/bin/hca", line 11, in <module>
    sys.exit(main())
  File "/home/natan/hca/dcp-cli/venv/lib/python3.6/site-packages/hca/cli.py", line 136, in main
    result = parsed_args.entry_point(parsed_args)
  File "/home/natan/hca/dcp-cli/venv/lib/python3.6/site-packages/hca/util/__init__.py", line 200, in _cli_call
    return self._consume_response(self._request(vars(cli_args)))
  File "/home/natan/hca/dcp-cli/venv/lib/python3.6/site-packages/hca/util/__init__.py", line 185, in _request
    raise SwaggerAPIException(response=res)
hca.util.exceptions.SwaggerAPIException: None: None (HTTP 403). Details:
{"message":"'eyJ0eXAiOiJKV1QiLCJhbGciOiJSUzI1NiIsImtpZCI6Ik1EYzJPVE0zT0RJNE9EWTJOVVU1UkVWR1JEVkVNME15T0VZd1FUa3pORFpEUkRsRVF6TkJSUSJ9.eyJodHRwczovL2F1dGguZGF0YS5odW1hbmNlbGxhdGxhcy5vcmcvZW1haWwiOiJuYWxhb0B1Y3NjLmVkdSIsImh0dHBzOi8vYXV0aC5kYXRhLmh1bWFuY2VsbGF0bGFzLm9yZy9ncm91cCI6ImhjYSIsImlzcyI6Imh0dHBzOi8vaHVtYW5jZWxsYXRsYXMuYXV0aDAuY29tLyIsInN1YiI6Imdvb2dsZS1vYXV0aDJ8MTE3NDI3ODMyNTYxMjczNzM3Mjg2IiwiYXVkIjpbImh0dHBzOi8vZGV2LmRhdGEuaHVtYW5jZWxsYXRsYXMub3JnLyIsImh0dHBzOi8vaHVtYW5jZWxsYXRsYXMuYXV0aDAuY29tL3VzZXJpbmZvIl0sImlhdCI6MTU1ODQ3MDI3OCwiZXhwIjoxNTU4NTU2Njc4LCJhenAiOiJxdE1nTms5ZnFWZWNsTHRabDZXa2JkSjU5ZFAzV2VBdCIsInNjb3BlIjoib3BlbmlkIGVtYWlsIG9mZmxpbmVfYWNjZXNzIn0.I0G2fQ5aAhCvPXgb7ncXtKL3a5F6Tvou6FSghU7s5bDipYzhmZHycp5kU_qHHjTCm6M52JD_2KafF9BLKMwysj4HDtkTu36ww9vqwcRDsJcOVuzWXUJMfMEPjAJADGj1ifsntXJP0NiobNJumLVPEsDiqGhMW_5LsYer7fHfWa7QHg_YBLI0lG5WlptfJH7CZ0KOhRB90Rj9aJ6FdeOMAD3CPuwyRP0qfMemVzXvs3haX2UzIEX5h7chQbAc2SemL6V_IqlJ8izEttrp5nike_7JwS_JPCPhVPjRMAdZX7-4SGned36mjtDg84gSy_El5JjWg15WwJer6604IAgfgA' not a valid key=value pair (missing equal-sign) in Authorization header: 'Bearer eyJ0eXAiOiJKV1QiLCJhbGciOiJSUzI1NiIsImtpZCI6Ik1EYzJPVE0zT0RJNE9EWTJOVVU1UkVWR1JEVkVNME15T0VZd1FUa3pORFpEUkRsRVF6TkJSUSJ9.eyJodHRwczovL2F1dGguZGF0YS5odW1hbmNlbGxhdGxhcy5vcmcvZW1haWwiOiJuYWxhb0B1Y3NjLmVkdSIsImh0dHBzOi8vYXV0aC5kYXRhLmh1bWFuY2VsbGF0bGFzLm9yZy9ncm91cCI6ImhjYSIsImlzcyI6Imh0dHBzOi8vaHVtYW5jZWxsYXRsYXMuYXV0aDAuY29tLyIsInN1YiI6Imdvb2dsZS1vYXV0aDJ8MTE3NDI3ODMyNTYxMjczNzM3Mjg2IiwiYXVkIjpbImh0dHBzOi8vZGV2LmRhdGEuaHVtYW5jZWxsYXRsYXMub3JnLyIsImh0dHBzOi8vaHVtYW5jZWxsYXRsYXMuYXV0aDAuY29tL3VzZXJpbmZvIl0sImlhdCI6MTU1ODQ3MDI3OCwiZXhwIjoxNTU4NTU2Njc4LCJhenAiOiJxdE1nTms5ZnFWZWNsTHRabDZXa2JkSjU5ZFAzV2VBdCIsInNjb3BlIjoib3BlbmlkIGVtYWlsIG9mZmxpbmVfYWNjZXNzIn0.I0G2fQ5aAhCvPXgb7ncXtKL3a5F6Tvou6FSghU7s5bDipYzhmZHycp5kU_qHHjTCm6M52JD_2KafF9BLKMwysj4HDtkTu36ww9vqwcRDsJcOVuzWXUJMfMEPjAJADGj1ifsntXJP0NiobNJumLVPEsDiqGhMW_5LsYer7fHfWa7QHg_YBLI0lG5WlptfJH7CZ0KOhRB90Rj9aJ6FdeOMAD3CPuwyRP0qfMemVzXvs3haX2UzIEX5h7chQbAc2SemL6V_IqlJ8izEttrp5nike_7JwS_JPCPhVPjRMAdZX7-4SGned36mjtDg84gSy_El5JjWg15WwJer6604IAgfgA'."}
```

**Comment by DailyDreaming** [comment]
@natanlao I can't reproduce this:
```
(v3nv) quokka@qcore:~/data-store$ pip install hca
Requirement already satisfied: hca in ./v3nv/lib/python3.6/site-packages (6.1.0)
Requirement already satisfied: awscli>1.15.70 in ./v3nv/lib/python3.6/site-packages (from hca) (1.16.164)
Requirement already satisfied: jsonpointer<2,>=1.10 in ./v3nv/lib/python3.6/site-packages (from hca) (1.14)
Requirement already satisfied: boto3>1.8 in ./v3nv/lib/python3.6/site-packages (from hca) (1.9.154)
Requirement already satisfied: botocore>=1.12.13 in ./v3nv/lib/python3.6/site-packages (from hca) (1.12.154)
Requirement already satisfied: argcomplete<2,>=1.9.3 in ./v3nv/lib/python3.6/site-packages (from hca) (1.10.0)
Requirement already satisfied: cryptography==2.3.1 in ./v3nv/lib/python3.6/site-packages (from hca) (2.3.1)
Requirement already satisfied: puremagic<1.5 in ./v3nv/lib/python3.6/site-packages (from hca) (1.4)
Requirement already satisfied: google-auth-oauthlib<2,>=0.1 in ./v3nv/lib/python3.6/site-packages (from hca) (0.3.0)
Requirement already satisfied: jsonschema<3,>=2.6 in ./v3nv/lib/python3.6/site-packages (from hca) (2.6.0)
Requirement already satisfied: atomicwrites<2,>=1.3.0 in ./v3nv/lib/python3.6/site-packages (from hca) (1.3.0)
Requirement already satisfied: tenacity<5.1,>=5.0.2 in ./v3nv/lib/python3.6/site-packages (from hca) (5.0.4)
Requirement already satisfied: commonmark<1,>=0.9.0 in ./v3nv/lib/python3.6/site-packages (from hca) (0.9.0)
Requirement already satisfied: google-auth<2,>=1.0.2 in ./v3nv/lib/python3.6/site-packages (from hca) (1.6.3)
Requirement already satisfied: PyJWT>=1.6.4 in ./v3nv/lib/python3.6/site-packages (from hca) (1.7.1)
Requirement already satisfied: Jinja2<3,>=2.9 in ./v3nv/lib/python3.6/site-packages (from hca) (2.10.1)
Requirement already satisfied: tweak<2,>=1.0.2 in ./v3nv/lib/python3.6/site-packages (from hca) (1.0.2)
Requirement already satisfied: rsa<=3.5.0,>=3.1.2 in ./v3nv/lib/python3.6/site-packages (from hca) (3.4.2)
Requirement already satisfied: requests<3,>=2.20.0 in ./v3nv/lib/python3.6/site-packages (from hca) (2.22.0)
Requirement already satisfied: six<2,>=1.10 in ./v3nv/lib/python3.6/site-packages (from hca) (1.12.0)
Requirement already satisfied: s3transfer<0.3.0,>=0.2.0 in ./v3nv/lib/python3.6/site-packages (from hca) (0.2.0)
Requirement already satisfied: dcplib<3,>=2.0.2 in ./v3nv/lib/python3.6/site-packages (from hca) (2.0.2)
Requirement already satisfied: docutils<1,>=0.14 in ./v3nv/lib/python3.6/site-packages (from hca) (0.14)
Requirement already satisfied: colorama<=0.3.9,>=0.2.5 in ./v3nv/lib/python3.6/site-packages (from awscli>1.15.70->hca) (0.3.9)
Requirement already satisfied: PyYAML<=3.13,>=3.10 in ./v3nv/lib/python3.6/site-packages (from awscli>1.15.70->hca) (3.13)
Requirement already satisfied: jmespath<1.0.0,>=0.7.1 in ./v3nv/lib/python3.6/site-packages (from boto3>1.8->hca) (0.9.4)
Requirement already satisfied: python-dateutil<3.0.0,>=2.1; python_version >= "2.7" in ./v3nv/lib/python3.6/site-packages (from botocore>=1.12.13->hca) (2.8.0)
Requirement already satisfied: urllib3<1.25,>=1.20; python_version >= "3.4" in ./v3nv/lib/python3.6/site-packages (from botocore>=1.12.13->hca) (1.24.1)
Requirement already satisfied: asn1crypto>=0.21.0 in ./v3nv/lib/python3.6/site-packages (from cryptography==2.3.1->hca) (0.24.0)
Requirement already satisfied: idna>=2.1 in ./v3nv/lib/python3.6/site-packages (from cryptography==2.3.1->hca) (2.8)
Requirement already satisfied: cffi!=1.11.3,>=1.7 in ./v3nv/lib/python3.6/site-packages (from cryptography==2.3.1->hca) (1.12.3)
Requirement already satisfied: argparse in ./v3nv/lib/python3.6/site-packages (from puremagic<1.5->hca) (1.4.0)
Requirement already satisfied: requests-oauthlib>=0.7.0 in ./v3nv/lib/python3.6/site-packages (from google-auth-oauthlib<2,>=0.1->hca) (1.2.0)
Requirement already satisfied: future in ./v3nv/lib/python3.6/site-packages (from commonmark<1,>=0.9.0->hca) (0.17.1)
Requirement already satisfied: cachetools>=2.0.0 in ./v3nv/lib/python3.6/site-packages (from google-auth<2,>=1.0.2->hca) (3.1.0)
Requirement already satisfied: pyasn1-modules>=0.2.1 in ./v3nv/lib/python3.6/site-packages (from google-auth<2,>=1.0.2->hca) (0.2.5)
Requirement already satisfied: MarkupSafe>=0.23 in ./v3nv/lib/python3.6/site-packages (from Jinja2<3,>=2.9->hca) (1.1.1)
Requirement already satisfied: pyasn1>=0.1.3 in ./v3nv/lib/python3.6/site-packages (from rsa<=3.5.0,>=3.1.2->hca) (0.4.5)
Requirement already satisfied: certifi>=2017.4.17 in ./v3nv/lib/python3.6/site-packages (from requests<3,>=2.20.0->hca) (2019.3.9)
Requirement already satisfied: chardet<3.1.0,>=3.0.2 in ./v3nv/lib/python3.6/site-packages (from requests<3,>=2.20.0->hca) (3.0.4)
Requirement already satisfied: crc32c in ./v3nv/lib/python3.6/site-packages (from dcplib<3,>=2.0.2->hca) (1.7)
Requirement already satisfied: pycparser in ./v3nv/lib/python3.6/site-packages (from cffi!=1.11.3,>=1.7->cryptography==2.3.1->hca) (2.19)
Requirement already satisfied: oauthlib>=3.0.0 in ./v3nv/lib/python3.6/site-packages (from requests-oauthlib>=0.7.0->google-auth-oauthlib<2,>=0.1->hca) (3.0.1)
You are using pip version 18.1, however version 19.1.1 is available.
You should consider upgrading via the 'pip install --upgrade pip' command.
(v3nv) quokka@qcore:~/data-store$ hca dss get-collections
{
  "collections": [
    {
      "uuid": "e9212ff7-86b7-4479-9111-c86521c4edf3",
      "version": "2019-05-07T163531.828088Z"
    },
    {
      "uuid": "b26f589a-2fe7-4161-8eb0-f8ca0282aa95",
      "version": "2019-05-07T162809.847327Z"
    }
  ]
}
```

What version and stage are you running this on?

**Comment by natanlao** [comment]
I can reproduce this on prod with `hca 6.1.0 (CPython 3.6.7 Linux-4.15.0-50-generic-x86_64-with-Ubuntu-18.04-bionic)`. Switching to dev resolved this issue for me.
