### ISSUE TITLE
Make sure port is open when using hca dss login.

### ISSUE THREAD

**Issue by DailyDreaming** [HumanCellAtlas/dcp-cli#352]
Just ran into this:

```
(v3nv) quokka@qcore:~/delete$ hca dss login
Traceback (most recent call last):
  File "/home/quokka/data-store/v3nv/bin/hca", line 11, in <module>
    sys.exit(main())
  File "/home/quokka/data-store/v3nv/lib/python3.6/site-packages/hca/cli.py", line 136, in main
    result = parsed_args.entry_point(parsed_args)
  File "/home/quokka/data-store/v3nv/lib/python3.6/site-packages/hca/util/__init__.py", line 575, in arg_forwarder
    return command(**command_args)
  File "/home/quokka/data-store/v3nv/lib/python3.6/site-packages/hca/util/__init__.py", line 409, in login
    credentials = flow.run_local_server(success_message=msg, audience=self._audience)
  File "/home/quokka/data-store/v3nv/lib/python3.6/site-packages/google_auth_oauthlib/flow.py", line 407, in run_local_server
    host, port, wsgi_app, handler_class=_WSGIRequestHandler)
  File "/usr/lib/python3.6/wsgiref/simple_server.py", line 153, in make_server
    server = server_class((host, port), handler_class)
  File "/usr/lib/python3.6/socketserver.py", line 453, in __init__
    self.server_bind()
  File "/usr/lib/python3.6/wsgiref/simple_server.py", line 50, in server_bind
    HTTPServer.server_bind(self)
  File "/usr/lib/python3.6/http/server.py", line 136, in server_bind
    socketserver.TCPServer.server_bind(self)
  File "/usr/lib/python3.6/socketserver.py", line 467, in server_bind
    self.socket.bind(self.server_address)
OSError: [Errno 98] Address already in use
```

**Comment by DailyDreaming** [comment]
See #353.  Using a different port blocks you, as the port 8080 is hard-coded into the whitelist of accepted `callback_url`s.

A suggested work-around (with credit to @Bento007 ): https://community.auth0.com/t/allowed-callback-urls-ending-with-a-wildcard/7626/2
