### ISSUE TITLE
hca dss put-bundle --files argument error

### ISSUE THREAD

**Issue by jeffrey856** [HumanCellAtlas/dcp-cli#391]
When attempting to run
`hca dss put-bundle --creator-uid 0 --uuid fff54b87-26fe-42a9-be54-3f5a7ef8176e --version 2019-03-26T131455.775610Z --replica aws --files '[{"uuid": "258080d4-1c7b-4a82-a95a-8842d9588618","version":"2019-02-26T195643.678045Z","name":"SRR6575901_2.fastq.gz","indexed":"False"}]'' --creator-uid 0` 

I ran into the error:

```
Traceback (most recent call last):
  File "/home/jeff/.local/bin/hca", line 10, in <module>
    sys.exit(main())
  File "/home/jeff/.local/lib/python3.6/site-packages/hca/cli.py", line 138, in main
    result = parsed_args.entry_point(parsed_args)
  File "/home/jeff/.local/lib/python3.6/site-packages/hca/util/__init__.py", line 200, in _cli_call
    return self._consume_response(self._request(vars(cli_args)))
  File "/home/jeff/.local/lib/python3.6/site-packages/hca/util/__init__.py", line 185, in _request
    raise SwaggerAPIException(response=res)
hca.util.exceptions.SwaggerAPIException: illegal_arguments: [{'uuid': '258080d4-1c7b-4a82-a95a-8842d9588618', 'version': '2019-02-26T195643.678045Z', 'name': 'SRR6575901_2.fastq.gz', 'indexed': 'False'}] is not of type 'object' (HTTP 400). Details:
Traceback (most recent call last):
  File "/var/task/chalicelib/dss/__init__.py", line 155, in wrapper
    return origwrapper(request)
  File "/opt/python/lib/python3.6/site-packages/connexion/decorators/validation.py", line 159, in wrapper
    error = self.validate_schema(data, request.url)
  File "/var/task/chalicelib/dss/__init__.py", line 146, in validate_schema
    raise DSSBindingException(result.body['detail'])
dss.error.DSSBindingException
```
It seems to trying to `load()` the input initially which turns it into a dictionary from a string. It then tries make sure it is an object from the swagger validation using that string.

**Comment by DailyDreaming** [comment]
Your command has `--creator-uid 0` twice and two single quotes where there should be one near the end of the command: `"indexed":"False"}]'' --creator-uid 0`.  That said, giving a corrected command gives `is not of type 'object' (HTTP 400)`.

This ticket should be to fix the input.

**Comment by jeffrey856** [comment]
I will take this issue up!

**Comment by natanlao** [comment]
`hca dss put-bundle --creator-uid 0 --uuid fff54b87-26fe-42a9-be54-3f5a7ef8176e --version 2019-03-26T131455.775610Z --replica aws --files '{"uuid": "258080d4-1c7b-4a82-a95a-8842d9588618","version":"2019-02-26T195643.678045Z","name":"SRR6575901_2.fastq.gz","indexed":false}'` works for me. I think that you specify multiples files not as objects in a json array but individually as arguments to `--files`.
