### ISSUE TITLE
Version conflict when installing with `pip install -e .`

### ISSUE THREAD

**Issue by jessebrennan** [HumanCellAtlas/dcp-cli#418]
To recreate:
```
$ virtualenv .venv -p python3.6
$ source .venv/bin/activate
$ pip --version
pip 19.2.1 from /home/jesse/gi/dcp-cli/.venv/lib/python3.6/site-packages/pip (python 3.6)
# be in base dir of repository
$ pip install -e .
$ hca dss download-manifest --replica aws --manifest manifest.tsv
Traceback (most recent call last):
  File "/home/jesse/gi/dcp-cli/.venv/lib/python3.6/site-packages/pkg_resources/__init__.py", line 574, in _build_master
    ws.require(__requires__)
  File "/home/jesse/gi/dcp-cli/.venv/lib/python3.6/site-packages/pkg_resources/__init__.py", line 892, in require
    needed = self.resolve(parse_requirements(requirements))
  File "/home/jesse/gi/dcp-cli/.venv/lib/python3.6/site-packages/pkg_resources/__init__.py", line 783, in resolve
    raise VersionConflict(dist, req).with_context(dependent_req)
pkg_resources.ContextualVersionConflict: (docutils 0.15.2 (/home/jesse/gi/dcp-cli/.venv/lib/python3.6/site-packages), Requirement.parse('docutils<0.15,>=0.10'), {'botocore', 'awscli'})

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/jesse/gi/dcp-cli/.venv/bin/hca", line 6, in <module>
    from pkg_resources import load_entry_point
  File "/home/jesse/gi/dcp-cli/.venv/lib/python3.6/site-packages/pkg_resources/__init__.py", line 3088, in <module>
    @_call_aside
  File "/home/jesse/gi/dcp-cli/.venv/lib/python3.6/site-packages/pkg_resources/__init__.py", line 3072, in _call_aside
    f(*args, **kwargs)
  File "/home/jesse/gi/dcp-cli/.venv/lib/python3.6/site-packages/pkg_resources/__init__.py", line 3101, in _initialize_master_working_set
    working_set = WorkingSet._build_master()
  File "/home/jesse/gi/dcp-cli/.venv/lib/python3.6/site-packages/pkg_resources/__init__.py", line 576, in _build_master
    return cls._build_from_requirements(__requires__)
  File "/home/jesse/gi/dcp-cli/.venv/lib/python3.6/site-packages/pkg_resources/__init__.py", line 589, in _build_from_requirements
    dists = ws.resolve(reqs, Environment())
  File "/home/jesse/gi/dcp-cli/.venv/lib/python3.6/site-packages/pkg_resources/__init__.py", line 783, in resolve
    raise VersionConflict(dist, req).with_context(dependent_req)
pkg_resources.ContextualVersionConflict: (docutils 0.15.2 (/home/jesse/gi/dcp-cli/.venv/lib/python3.6/site-packages), Requirement.parse('docutils<0.15,>=0.10'), {'botocore', 'awscli'})
```

Fix for me locally, was to pin `docutils==0.14`. PR coming soon.

**Comment by natanlao** [comment]
I can reproduce this bug.

```
> uname -a
Darwin eduroam-169-233-161-29.ucsc.edu 18.7.0 Darwin Kernel Version 18.7.0: Thu Jun 20 18:42:21 PDT 2019; root:xnu-4903.270.47~4/RELEASE_X86_64 x86_64
```

```
> python --version
Python 3.7.4
```

```
> pip install git+git://github.com/HumanCellAtlas/dcp-cli@f2fb9387c055181997bc2c0cea61a8bf6ae35790#egg=hca
Collecting hca from git+git://github.com/HumanCellAtlas/dcp-cli@f2fb9387c055181997bc2c0cea61a8bf6ae35790#egg=hca
  Cloning git://github.com/HumanCellAtlas/dcp-cli (to revision f2fb9387c055181997bc2c0cea61a8bf6ae35790) to /private/var/folders/n9/jy57d8zd7z92_21t7jx282y80000gn/T/pip-install-ylmduvji/hca
Collecting argcomplete<2,>=1.9.3 (from hca)
  Using cached https://files.pythonhosted.org/packages/4d/82/f44c9661e479207348a979b1f6f063625d11dc4ca6256af053719bbb0124/argcomplete-1.10.0-py2.py3-none-any.whl
Collecting atomicwrites<2,>=1.3.0 (from hca)
  Using cached https://files.pythonhosted.org/packages/52/90/6155aa926f43f2b2a22b01be7241be3bfd1ceaf7d0b3267213e8127d41f4/atomicwrites-1.3.0-py2.py3-none-any.whl
Collecting awscli>1.15.70 (from hca)
  Using cached https://files.pythonhosted.org/packages/aa/60/61d4abc71f2731f1d10fb7c74edcfa2ff1e4f0656ed47c29d5c9223896cf/awscli-1.16.213-py2.py3-none-any.whl
Collecting boto3>1.8 (from hca)
  Using cached https://files.pythonhosted.org/packages/78/a4/1448a8c827d19ab49b98fc6767bb2cf689386ef8102502cbc956d4faa638/boto3-1.9.203-py2.py3-none-any.whl
Collecting botocore>=1.12.13 (from hca)
  Using cached https://files.pythonhosted.org/packages/78/ab/168a3ec74ab3f6e1aa066ef3c77082749017345cbb2ccb1477ed2f21d19b/botocore-1.12.203-py2.py3-none-any.whl
Collecting commonmark<1,>=0.9.0 (from hca)
  Using cached https://files.pythonhosted.org/packages/a7/65/2ea45a38e8c6a0a13453c5cadcc9b725049425c8628dbe7da87b30944573/commonmark-0.9.0-py2.py3-none-any.whl
Collecting cryptography==2.3.1 (from hca)
  Using cached https://files.pythonhosted.org/packages/98/0b/a6f293e5f10095dd8657a1b125c1ba6995c59d39cd8e20355475c8f760d0/cryptography-2.3.1-cp34-abi3-macosx_10_6_intel.whl
Collecting dcplib<3,>=2.0.2 (from hca)
  Using cached https://files.pythonhosted.org/packages/21/e0/a5eb2f14d7675f60f3e290f329367619ebe2911163186255c2e5abc30594/dcplib-2.1.2-py3-none-any.whl
Collecting docutils<1,>=0.14 (from hca)
  Using cached https://files.pythonhosted.org/packages/22/cd/a6aa959dca619918ccb55023b4cb151949c64d4d5d55b3f4ffd7eee0c6e8/docutils-0.15.2-py3-none-any.whl
Collecting google-auth<2,>=1.0.2 (from hca)
  Using cached https://files.pythonhosted.org/packages/c5/9b/ed0516cc1f7609fb0217e3057ff4f0f9f3e3ce79a369c6af4a6c5ca25664/google_auth-1.6.3-py2.py3-none-any.whl
Collecting google-auth-oauthlib<2,>=0.1 (from hca)
  Using cached https://files.pythonhosted.org/packages/74/a2/1323b1bce9935ac948cd4863509de16cf852cd80b12dd29e648c65fea93d/google_auth_oauthlib-0.4.0-py2.py3-none-any.whl
Collecting Jinja2<3,>=2.9 (from hca)
  Using cached https://files.pythonhosted.org/packages/1d/e7/fd8b501e7a6dfe492a433deb7b9d833d39ca74916fa8bc63dd1a4947a671/Jinja2-2.10.1-py2.py3-none-any.whl
Collecting jsonpointer<2,>=1.10 (from hca)
  Using cached https://files.pythonhosted.org/packages/7b/f4/90449441c1c011a733ee85739a680f2442eda2130e6a88f51804660a0289/jsonpointer-1.14-py2.py3-none-any.whl
Collecting jsonschema<3,>=2.6 (from hca)
  Using cached https://files.pythonhosted.org/packages/77/de/47e35a97b2b05c2fadbec67d44cfcdcd09b8086951b331d82de90d2912da/jsonschema-2.6.0-py2.py3-none-any.whl
Collecting puremagic<1.5 (from hca)
  Using cached https://files.pythonhosted.org/packages/19/fe/343eabd56fd290f6a8b3e32512f8cd368f49eaf7eae57d70a987bd19ff44/puremagic-1.4-py3-none-any.whl
Collecting PyJWT>=1.6.4 (from hca)
  Using cached https://files.pythonhosted.org/packages/87/8b/6a9f14b5f781697e51259d81657e6048fd31a113229cf346880bb7545565/PyJWT-1.7.1-py2.py3-none-any.whl
Collecting requests<3,>=2.20.0 (from hca)
  Using cached https://files.pythonhosted.org/packages/51/bd/23c926cd341ea6b7dd0b2a00aba99ae0f828be89d72b2190f27c11d4b7fb/requests-2.22.0-py2.py3-none-any.whl
Collecting rsa<=3.5.0,>=3.1.2 (from hca)
  Using cached https://files.pythonhosted.org/packages/e1/ae/baedc9cb175552e95f3395c43055a6a5e125ae4d48a1d7a924baca83e92e/rsa-3.4.2-py2.py3-none-any.whl
Collecting s3transfer<0.3.0,>=0.2.0 (from hca)
  Using cached https://files.pythonhosted.org/packages/16/8a/1fc3dba0c4923c2a76e1ff0d52b305c44606da63f718d14d3231e21c51b0/s3transfer-0.2.1-py2.py3-none-any.whl
Collecting six<2,>=1.10 (from hca)
  Using cached https://files.pythonhosted.org/packages/73/fb/00a976f728d0d1fecfe898238ce23f502a721c0ac0ecfedb80e0d88c64e9/six-1.12.0-py2.py3-none-any.whl
Collecting tenacity<5.1,>=5.0.2 (from hca)
  Using cached https://files.pythonhosted.org/packages/6a/93/dfcf5b1b46ab29196274b78dcba69fab5e54b6dc303a7eed90a79194d277/tenacity-5.0.4-py2.py3-none-any.whl
Collecting tweak<2,>=1.0.2 (from hca)
  Using cached https://files.pythonhosted.org/packages/97/61/f4cdd589683d774db99032769e6387747eac32eb0a547e07b855c54fadd6/tweak-1.0.3-py2.py3-none-any.whl
Collecting colorama<=0.3.9,>=0.2.5 (from awscli>1.15.70->hca)
  Using cached https://files.pythonhosted.org/packages/db/c8/7dcf9dbcb22429512708fe3a547f8b6101c0d02137acbd892505aee57adf/colorama-0.3.9-py2.py3-none-any.whl
Collecting PyYAML<=5.1,>=3.10; python_version != "2.6" (from awscli>1.15.70->hca)
Collecting jmespath<1.0.0,>=0.7.1 (from boto3>1.8->hca)
  Using cached https://files.pythonhosted.org/packages/83/94/7179c3832a6d45b266ddb2aac329e101367fbdb11f425f13771d27f225bb/jmespath-0.9.4-py2.py3-none-any.whl
Collecting urllib3<1.26,>=1.20; python_version >= "3.4" (from botocore>=1.12.13->hca)
  Using cached https://files.pythonhosted.org/packages/e6/60/247f23a7121ae632d62811ba7f273d0e58972d75e58a94d329d51550a47d/urllib3-1.25.3-py2.py3-none-any.whl
Collecting python-dateutil<3.0.0,>=2.1; python_version >= "2.7" (from botocore>=1.12.13->hca)
  Using cached https://files.pythonhosted.org/packages/41/17/c62faccbfbd163c7f57f3844689e3a78bae1f403648a6afb1d0866d87fbb/python_dateutil-2.8.0-py2.py3-none-any.whl
Collecting future (from commonmark<1,>=0.9.0->hca)
Collecting asn1crypto>=0.21.0 (from cryptography==2.3.1->hca)
  Using cached https://files.pythonhosted.org/packages/ea/cd/35485615f45f30a510576f1a56d1e0a7ad7bd8ab5ed7cdc600ef7cd06222/asn1crypto-0.24.0-py2.py3-none-any.whl
Collecting idna>=2.1 (from cryptography==2.3.1->hca)
  Using cached https://files.pythonhosted.org/packages/14/2c/cd551d81dbe15200be1cf41cd03869a46fe7226e7450af7a6545bfc474c9/idna-2.8-py2.py3-none-any.whl
Collecting cffi!=1.11.3,>=1.7 (from cryptography==2.3.1->hca)
  Using cached https://files.pythonhosted.org/packages/f0/48/5aa4ea664eba26dd5142558d04762f5065c02220b4665b3f7eecb9bb614e/cffi-1.12.3-cp37-cp37m-macosx_10_9_x86_64.whl
Collecting crc32c (from dcplib<3,>=2.0.2->hca)
  Using cached https://files.pythonhosted.org/packages/30/24/dd3284a745dde844914cace5995669848282bf7fbc0a7c5dce37f64e72cf/crc32c-1.7-cp37-cp37m-macosx_10_6_intel.whl
Collecting cachetools>=2.0.0 (from google-auth<2,>=1.0.2->hca)
  Using cached https://files.pythonhosted.org/packages/2f/a6/30b0a0bef12283e83e58c1d6e7b5aabc7acfc4110df81a4471655d33e704/cachetools-3.1.1-py2.py3-none-any.whl
Collecting pyasn1-modules>=0.2.1 (from google-auth<2,>=1.0.2->hca)
  Using cached https://files.pythonhosted.org/packages/be/70/e5ea8afd6d08a4b99ebfc77bd1845248d56cfcf43d11f9dc324b9580a35c/pyasn1_modules-0.2.6-py2.py3-none-any.whl
Collecting requests-oauthlib>=0.7.0 (from google-auth-oauthlib<2,>=0.1->hca)
  Using cached https://files.pythonhosted.org/packages/c2/e2/9fd03d55ffb70fe51f587f20bcf407a6927eb121de86928b34d162f0b1ac/requests_oauthlib-1.2.0-py2.py3-none-any.whl
Collecting MarkupSafe>=0.23 (from Jinja2<3,>=2.9->hca)
  Using cached https://files.pythonhosted.org/packages/ce/c6/f000f1af136ef74e4a95e33785921c73595c5390403f102e9b231b065b7a/MarkupSafe-1.1.1-cp37-cp37m-macosx_10_6_intel.whl
Collecting argparse (from puremagic<1.5->hca)
  Using cached https://files.pythonhosted.org/packages/f2/94/3af39d34be01a24a6e65433d19e107099374224905f1e0cc6bbe1fd22a2f/argparse-1.4.0-py2.py3-none-any.whl
Collecting chardet<3.1.0,>=3.0.2 (from requests<3,>=2.20.0->hca)
  Using cached https://files.pythonhosted.org/packages/bc/a9/01ffebfb562e4274b6487b4bb1ddec7ca55ec7510b22e4c51f14098443b8/chardet-3.0.4-py2.py3-none-any.whl
Collecting certifi>=2017.4.17 (from requests<3,>=2.20.0->hca)
  Using cached https://files.pythonhosted.org/packages/69/1b/b853c7a9d4f6a6d00749e94eb6f3a041e342a885b87340b79c1ef73e3a78/certifi-2019.6.16-py2.py3-none-any.whl
Collecting pyasn1>=0.1.3 (from rsa<=3.5.0,>=3.1.2->hca)
  Using cached https://files.pythonhosted.org/packages/6a/6e/209351ec34b7d7807342e2bb6ff8a96eef1fd5dcac13bdbadf065c2bb55c/pyasn1-0.4.6-py2.py3-none-any.whl
Collecting pycparser (from cffi!=1.11.3,>=1.7->cryptography==2.3.1->hca)
Collecting oauthlib>=3.0.0 (from requests-oauthlib>=0.7.0->google-auth-oauthlib<2,>=0.1->hca)
  Using cached https://files.pythonhosted.org/packages/05/57/ce2e7a8fa7c0afb54a0581b14a65b56e62b5759dbc98e80627142b8a3704/oauthlib-3.1.0-py2.py3-none-any.whl
botocore 1.12.203 has requirement docutils<0.15,>=0.10, but you'll have docutils 0.15.2 which is incompatible.
awscli 1.16.213 has requirement docutils<0.15,>=0.10, but you'll have docutils 0.15.2 which is incompatible.
Installing collected packages: argcomplete, atomicwrites, colorama, urllib3, docutils, jmespath, six, python-dateutil, botocore, PyYAML, pyasn1, rsa, s3transfer, awscli, boto3, future, commonmark, asn1crypto, idna, pycparser, cffi, cryptography, argparse, puremagic, crc32c, chardet, certifi, requests, dcplib, cachetools, pyasn1-modules, google-auth, oauthlib, requests-oauthlib, google-auth-oauthlib, MarkupSafe, Jinja2, jsonpointer, jsonschema, PyJWT, tenacity, tweak, hca
  Running setup.py install for hca ... done
Successfully installed Jinja2-2.10.1 MarkupSafe-1.1.1 PyJWT-1.7.1 PyYAML-5.1 argcomplete-1.10.0 argparse-1.4.0 asn1crypto-0.24.0 atomicwrites-1.3.0 awscli-1.16.213 boto3-1.9.203 botocore-1.12.203 cachetools-3.1.1 certifi-2019.6.16 cffi-1.12.3 chardet-3.0.4 colorama-0.3.9 commonmark-0.9.0 crc32c-1.7 cryptography-2.3.1 dcplib-2.1.2 docutils-0.15.2 future-0.17.1 google-auth-1.6.3 google-auth-oauthlib-0.4.0 hca-6.4.0 idna-2.8 jmespath-0.9.4 jsonpointer-1.14 jsonschema-2.6.0 oauthlib-3.1.0 puremagic-1.4 pyasn1-0.4.6 pyasn1-modules-0.2.6 pycparser-2.19 python-dateutil-2.8.0 requests-2.22.0 requests-oauthlib-1.2.0 rsa-3.4.2 s3transfer-0.2.1 six-1.12.0 tenacity-5.0.4 tweak-1.0.3 urllib3-1.25.3
You are using pip version 19.0.3, however version 19.2.1 is available.
You should consider upgrading via the 'pip install --upgrade pip' command.
```

Note that `pip` raises a warning (reproduced):

```
botocore 1.12.203 has requirement docutils<0.15,>=0.10, but you'll have docutils 0.15.2 which is incompatible.
awscli 1.16.213 has requirement docutils<0.15,>=0.10, but you'll have docutils 0.15.2 which is incompatible.
```

Bug can be reproduced by running any command:

```
> hca
Traceback (most recent call last):
  File "/Users/natan/hca/dcp-cli/venv-test/lib/python3.7/site-packages/pkg_resources/__init__.py", line 583, in _build_master
    ws.require(__requires__)
  File "/Users/natan/hca/dcp-cli/venv-test/lib/python3.7/site-packages/pkg_resources/__init__.py", line 900, in require
    needed = self.resolve(parse_requirements(requirements))
  File "/Users/natan/hca/dcp-cli/venv-test/lib/python3.7/site-packages/pkg_resources/__init__.py", line 791, in resolve
    raise VersionConflict(dist, req).with_context(dependent_req)
pkg_resources.ContextualVersionConflict: (docutils 0.15.2 (/Users/natan/hca/dcp-cli/venv-test/lib/python3.7/site-packages), Requirement.parse('docutils<0.15,>=0.10'), {'botocore', 'awscli'})

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/Users/natan/hca/dcp-cli/venv-test/bin/hca", line 6, in <module>
    from pkg_resources import load_entry_point
  File "/Users/natan/hca/dcp-cli/venv-test/lib/python3.7/site-packages/pkg_resources/__init__.py", line 3191, in <module>
    @_call_aside
  File "/Users/natan/hca/dcp-cli/venv-test/lib/python3.7/site-packages/pkg_resources/__init__.py", line 3175, in _call_aside
    f(*args, **kwargs)
  File "/Users/natan/hca/dcp-cli/venv-test/lib/python3.7/site-packages/pkg_resources/__init__.py", line 3204, in _initialize_master_working_set
    working_set = WorkingSet._build_master()
  File "/Users/natan/hca/dcp-cli/venv-test/lib/python3.7/site-packages/pkg_resources/__init__.py", line 585, in _build_master
    return cls._build_from_requirements(__requires__)
  File "/Users/natan/hca/dcp-cli/venv-test/lib/python3.7/site-packages/pkg_resources/__init__.py", line 598, in _build_from_requirements
    dists = ws.resolve(reqs, Environment())
  File "/Users/natan/hca/dcp-cli/venv-test/lib/python3.7/site-packages/pkg_resources/__init__.py", line 791, in resolve
    raise VersionConflict(dist, req).with_context(dependent_req)
pkg_resources.ContextualVersionConflict: (docutils 0.15.2 (/Users/natan/hca/dcp-cli/venv-test/lib/python3.7/site-packages), Requirement.parse('docutils<0.15,>=0.10'), {'botocore', 'awscli'})
```

At first glance, this sounds like pypa/pip#988 to me, but I haven't confirmed that.
